- hosts: ansibletower
  become_user: root
  become: true
  tasks:
    - name: Install software properties
      become: true
      command: apt-get install software-properties-common
    - name: Add repository
      become: true
      expect:
      command: apt-add-repository ppa:ansible/ansible
      responses:
        'PRESS \<ENTER\> TO CONTINUE:': ''
    - name: Update
      become: true
      command: apt-get update
    - name: Install Ansible
      become: true
      command: apt-get install ansible
