- hosts: ansibletower
  become_user: root
  become: true
  tasks:
    - name: install pip
      command: apt-get install python-pip -y
      become: true
    - name: install pexpect
      pip:
        name: pexpect
      become: yes
    - name: Install software properties
      become: true
      command: apt-get install software-properties-common
    - name: Add repository
      apt_repository: repo='ppa:ansible/ansible' state=present
      become: true
    - name: Update
      become: true
      command: apt-get update
    - name: Install Ansible
      become: true
      command: apt-get install ansible -y
    - name: Download Tower
      become: true
      command: wget "https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz"
    - name: Extract folder
      become: true
      command: tar xvzf ansible-tower-setup-latest.tar.gz
    - name: Change inventory file
      - lineinfile:
        path: /etc/hosts
        regexp: 'admin_password='
        line: 'admin_password='P@ssw0rd2018''
        owner: root

