- hosts: ansibletower
  become_user: root
  become: true
  tasks:
    - name: Install software properties
      become: true
      command: apt-get install software-properties-common
    - name: Add repository
      apt_repository: repo='ppa:ansible/ansible' state=present
      become: true
    - name: Update
      become: true
      command: apt-get update
    - name: Install Ansible
      become: true
      command: apt-get install ansible -y
    - name: Download Tower
      become: true
      command: wget "https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz"
    - name: Extract folder
      become: true
      command: tar xvzf ansible-tower-setup-latest.tar.gz
    - name: Change inventory file
      lineinfile:
        path: /home/WMA_Admin/ansible-tower-setup-3.4.1-1/inventory
        regexp: 'admin_password='
        line: 'admin_password=Test123456789!'
        owner: root
    - name: Change inventory file
      lineinfile:
        path: /home/WMA_Admin/ansible-tower-setup-3.4.1-1/inventory
        regexp: 'pg_password='
        line: 'pg_password=Test123456789!'
        owner: root
    - name: Change inventory file
      lineinfile:
        path: /home/WMA_Admin/ansible-tower-setup-3.4.1-1/inventory
        regexp: 'rabbitmq_password='
        line: 'rabbitmq_password=Test123456789!'
        owner: root
    - name: Insert a line at the end of a file.
      lineinfile:
        path: /home/WMA_Admin/ansible-tower-setup-3.4.1-1/inventory
        line: 'rabbitmq_port=5672'
    - name: Insert a line at the end of a file.
      lineinfile:
        path: /home/WMA_Admin/ansible-tower-setup-3.4.1-1/inventory
        line: 'rabbitmq_vhost=tower'
    - name: Copy and Execute the script 
      script: /home/WMA_Admin/ansible-tower-setup-3.4.1-1/setup.sh
      become: true

