- hosts: ansibletower
  become: true
  tasks:
    - name: Install software properties
      command: apt-get install software-properties-common
    - name: Add repository
      command: apt-add-repository ppa:ansible/ansible
    - name: Update
      command: apt-get update
    - name: Install Ansible
      command: apt-get install ansible
