- hosts: ansibletower
  tasks:
    - name: Install software properties
      command: apt-get install software-properties-common
      become: true
    - name: Add repository
      command: apt-add-repository ppa:ansible/ansible
      become: true
    - name: Update
      command: apt-get update
      become: true
    - name: Install Ansible
      command: apt-get install ansible
      become: true
