[windows]
10.0.1.4

[windows:vars]
ansible_user=WMA_Admin
ansible_password=P@ssw0rd2018
ansible_port=5985
ansible_connection=winrm
ansible_winrm_scheme=http
ansible_winrm_server_cert_validation=ignore
