- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: zuyrg00003
    vm_name: harrypotter
    location: westeurope
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: zuyrg00003
      name: harrypottervn
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: zuyrg00003
      name: harrypottersubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: harrypottervn
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: zuyrg00003
      allocation_method: Static
      name: harrypotterpublic
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: zuyrg00003
      name: harrypotternsg
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: zuyrg00003
      name: harrypotterif
      virtual_network: harrypottervn
      subnet: harrypottersubnet
      public_ip_name: harrypotterpublic
      security_group: harrypotternsg
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: zuyrg00003
      name: harrypottervm
      vm_size: Standard_B1s
      admin_username: azureuser
      admin_password: Password@123
      network_interfaces: harrypotterif
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest
