- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: zuyrg00003
    vm_name: testvm
    location: westeu
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: zuyrg00003
      name: testvn
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: zuyrg00003
      name: testsubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: testvn
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: zuyrg00003
      allocation_method: Static
      name: testpublic
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: zuyrg00003
      name: testnsg
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: zuyrg00003
      name: testif
      virtual_network: testvn
      subnet: testsubnet
      public_ip_name: testpublic
      security_group: testnsg
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: zuyrg00003
      name: testvm
      vm_size: Standard_B1s
      admin_username: "{{ server.username }}"
      admin_password: "{{ server.password }}"
      network_interfaces: testif
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest
