- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: zuyrg00003
    vm_name: WMA
    location: westeu
    username: WMA_Admin
    password: P@ssw0rd201888
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_vn"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_subnet"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vm_name }}_vn"
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ vm_name }}_publicIP"
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_nsg"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_NICweb01"
      virtual_network: "{{ vm_name }}_vn"
      subnet: "{{ vm_name }}_subnet"
      public_ip_name: "{{ vm_name }}_publicIP"
      security_group: "{{ vm_name }}_nsg"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}WEB01"
      vm_size: Standard_B1s
      storage_account: WMA_StorageAccountWEB01
      os_type: Windows
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
      network_interfaces: "{{ vm_name }}_NICweb01"
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
        
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_NICweb02"
      virtual_network: "{{ vm_name }}_vn"
      subnet: "{{ vm_name }}_subnet"
      public_ip_name: "{{ vm_name }}_publicIP"
      security_group: "{{ vm_name }}_nsg"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}WEB02"
      vm_size: Standard_B1s
      storage_account: WMA_StorageAccountWEB02
      os_type: Windows
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
      network_interfaces: "{{ vm_name }}_NICweb02"
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
