- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: zuyrg00003
    vm_name: WMA
    location: westeu
    username: WMA_Admin
    password: P@ssw0rd2018
  
  tasks:
  - name: Create an availability set
    azure_rm_availabilityset:
      name: WMAavailabilityset
      resource_group: "{{ resource_group }}"
      
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ vm_name }}_publicIP"
      
  - name: create load balancer
    azure_rm_loadbalancer:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_LoadBalancer"
      frontend_ip_configurations:
        - name: frontendIPconf
          public_ip_address: "{{ vm_name }}_publicIP"
      backend_address_pools:
        - name: backendaddrpoolWEB
        - name: backendaddrpoolMGT
      probes:
        - name: probHTTP
          protocol: Tcp
          port: 80
          fail_count: 3
          interval: 15
        - name: probHTTPS
          protocol: Tcp
          port: 443
          fail_count: 3
          interval: 15
        - name: probRDP
          protocol: Tcp
          port: 3389
          fail_count: 3
          interval: 15
      load_balancing_rules:
        - name: loadbalancingrulesHTTP
          frontend_ip_configuration: frontendIPconf
          protocol: Tcp
          frontend_port: 80
          backend_port: 80
          backend_address_pool: backendaddrpoolWEB
          probe: probHTTP
        - name: loadbalancingrulesHTTPS
          frontend_ip_configuration: frontendIPconf
          protocol: Tcp
          frontend_port: 443
          backend_port: 443
          backend_address_pool: backendaddrpoolWEB
          probe: probHTTPS
        - name: loadbalancingrulesRDP
          frontend_ip_configuration: frontendIPconf
          protcool: Tcp
          frontend_port: 3389
          back-end_port: 3389
          backend_Address_pool: backendaddrpoolMGT
          probe: probRDP
    
  - name: Create storage account WEB01
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: wmastorageaccountweb01
      account_type: Standard_LRS
      
  - name: Create storage account WEB02
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: wmastorageaccountweb02
      account_type: Standard_LRS
      
  - name: Create storage account WMAManagement
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: wmastorageaccountmanage
      account_type: Standard_LRS
      
  - name: Create virtual network Frontend
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_vn"
      address_prefixes: "10.0.0.0/16"
      
  - name: Add subnet Frontend
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_subnet"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vm_name }}_vn"
      
  - name: Create Network Security Group that allows RDP
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_nsg"
      rules:
        - name: RDP
          protocol: Tcp
          destination_address_prefix:
            - '10.0.1.6'
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound
        - name: HTTPandHTTPS
          protocol: Tcp
          destination_address_prefix:
            - '10.0.1.4'
            - '10.0.1.5'
          destination_port_range:
            - 80
            - 443
          access: Allow
          priority: 102
          
  - name: Create virtual network interface card WEB01
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_NICweb01"
      virtual_network: "{{ vm_name }}_vn"
      subnet: "{{ vm_name }}_subnet"
      security_group: "{{ vm_name }}_nsg"
      ip_configurations:
        - name: ipconfig1
          load_balancer_backend_address_pools:
            - name: backendaddrpoolWEB
              load_balancer: "{{ vm_name }}_LoadBalancer"
      
  - name: Create VM WEB01
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}WEB01"
      vm_size: Standard_B2s
      storage_account: wmastorageaccountweb01
      os_type: Windows
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
      availability_set: WMAavailabilityset
      network_interfaces: "{{ vm_name }}_NICweb01"
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
        
  - name: Create virtual network interface card WEB02
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_NICweb02"
      virtual_network: "{{ vm_name }}_vn"
      subnet: "{{ vm_name }}_subnet"
      security_group: "{{ vm_name }}_nsg"
      ip_configurations:
        - name: ipconfig1
          load_balancer_backend_address_pools:
            - name: backendaddrpoolWEB
              load_balancer: "{{ vm_name }}_LoadBalancer"
      
  - name: Create VM WEB02
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}WEB02"
      vm_size: Standard_B2s
      storage_account: wmastorageaccountweb02
      os_type: Windows
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
      availability_set: WMAavailabilityset
      network_interfaces: "{{ vm_name }}_NICweb02"
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
        
  - name: Create virtual network interface card WMAManagement
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_NICmanagement"
      virtual_network: "{{ vm_name }}_vn"
      subnet: "{{ vm_name }}_subnet"
      security_group: "{{ vm_name }}_nsg"
      ip_configurations:
      - name: ipconfig1
        load_balancer_backend_address_pools:
          - name: backendaddrpoolMGT
            load_balancer: "{{ vm_name }}_LoadBalancer"
      
  - name: Create VM WMAManagement
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}Management"
      vm_size: Standard_B2s
      storage_account: wmastorageaccountmanage
      os_type: Windows
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
      availability_set: WMAavailabilityset
      network_interfaces: "{{ vm_name }}_NICmanagement"
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
