- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: zuyrg00003
    vm_name: test
    location: westeu
    username: azureuser
    password: Password@123
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: zuyrg00003
      name: testvn
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: zuyrg00003
      name: testsubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: testvn
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: zuyrg00003
      allocation_method: Static
      name: testpublic
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: zuyrg00003
      name: testnsg
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: zuyrg00003
      name: testif
      virtual_network: testvn
      subnet: testsubnet
      public_ip_name: testpublic
      security_group: testnsg
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: zuyrg00003
      name: testvm
      vm_size: Standard_B1s
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
      network_interfaces: testif
      image:
        offer: WindowsServer
        publisher: Microsoft
        sku: 2016
        version: latest
  - name: Install AD Services feature
    win_feature:
      name: AD-Domain-Services
      include_management_tools: yes
      include_sub_features: yes
      state: present
      register: result

  - name: Create new forest
    win_domain:
      dns_domain_name: tycho.local
      safe_mode_password: RememberTheCant!
      register: result

  - name: Reboot after creation
    win_reboot:
      msg: "Server config in progress; rebooting..."
      when: result.reboot_required        
