- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: zuyrg00003
    vm_name: WMA
    location: westeu
    username: WMA_Admin
    password: P@ssw0rd2018
  tasks:
  
  - name: Create storage account WEB01
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: wmastorageaccountweb01
      account_type: Standard_LRS
      
  - name: Create storage account WEB02
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: wmastorageaccountweb02
      account_type: Standard_LRS
      
  - name: Create storage account WMAManagement
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: wmastorageaccountmanage
      account_type: Standard_LRS
      
  - name: Create virtual network Frontend
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_vn"
      address_prefixes: "10.0.0.0/16"
      
  - name: Add subnet Frontend
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_subnet"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vm_name }}_vn"
      
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ vm_name }}_publicIP"
      
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_nsg"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
          
  - name: Create virtual network interface card WEB01
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_NICweb01"
      virtual_network: "{{ vm_name }}_vn"
      subnet: "{{ vm_name }}_subnet"
      security_group: "{{ vm_name }}_nsg"
      
  - name: Create VM WEB01
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}WEB01"
      vm_size: Standard_B1s
      storage_account: wmastorageaccountweb01
      os_type: Windows
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
      network_interfaces: "{{ vm_name }}_NICweb01"
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
        
  - name: Create virtual network interface card WEB02
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_NICweb02"
      virtual_network: "{{ vm_name }}_vn"
      subnet: "{{ vm_name }}_subnet"
      security_group: "{{ vm_name }}_nsg"
      
  - name: Create VM WEB02
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}WEB02"
      vm_size: Standard_B1s
      storage_account: wmastorageaccountweb02
      os_type: Windows
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
      network_interfaces: "{{ vm_name }}_NICweb02"
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest    
        
  - name: Create virtual network interface card WMAManagement
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}_NICmanagement"
      virtual_network: "{{ vm_name }}_vn"
      subnet: "{{ vm_name }}_subnet"
      security_group: "{{ vm_name }}_nsg"
      
  - name: Create VM WMAManagement
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}Management"
      vm_size: Standard_B1s
      storage_account: wmastorageaccountmanage
      os_type: Windows
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
      network_interfaces: "{{ vm_name }}_NICmanagement"
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
        
  - name: create load balancer
    azure_rm_loadbalancer:
      resource_group: "{{ resource_group }}"
      name: WMALoadBalancer
      frontend_ip_configurations:
        - name: FrontendIPconf
          public_ip_address: "{{ vm_name }}_publicIP"
      backend_address_pools:
        - name: backendaddrpoolWEB
      probes:
        - name: "{{ vm_name }}WEB02"
          port: 80
      inbound_nat_pools:
        - name: inboundnatpool0
          frontend_ip_configuration_name: FrontendIPconf
          protocol: Tcp
          frontend_port_range_start: 80
          frontend_port_range_end: 81
          backend_port: 8080
      load_balancing_rules:
        - name: lbrbalancingrule0
          frontend_ip_configuration: FrontendIP
          backend_address_pool: backendaddrpoolWEB
          frontend_port: 80
          backend_port: 80
          probe: "{{ vm_name }}WEB02"
