- hosts: webservers
  tasks:
    - name: Install IIS (Web-Server only)
      win_feature:
        name: Web-Server
        state: present
        
    - name: create Temp directory
      win_file:
        path: C:\temp
        state: directory
    
    - name: Copy certificate
      win_copy:
        src: /home/WMA_Admin/wma.westeurope.cloudapp.azure.com.pfx
        dest: C:\temp\wma.westeurope.cloudapp.azure.com.pfx
        
    - name: import certificate
      win_certificate_store:
        path: C:\temp\wma.westeurope.cloudapp.azure.com.pfx
        state: present
        password: P@ssw0rd2018
      
    - name: Add HTTPS binding
      win_iis_webbinding:
        name: Default Web Site
        protocol: https
        port: 443
        host_header: wma.westeurope.cloudapp.azure.com
        ssl_flags: 1
        certificate_hash: 712a3ccf4cf6ecb8747722b972ff6b0a291ac2b0
        state: present
        
- hosts: domeincontrollers
  tasks:
    - name: Install AD-Domain-Services feature
      win_feature: >
        name=AD-Domain-Services
        include_management_tools=yes
        include_sub_features=yes
        state=present
  
    - name: Create Active Directory Domain Controller
      win_domain:
        dns_domain_name: wma.local
        safe_mode_password: P@ssw0rd2018
      register: active_directory_controllers

    - name: Reboot once Domain Controller is created
      win_reboot:
      when: active_directory_controllers.reboot_required
      
- hosts: domeincontrollers
  tasks:
    - name: Add server to domain
      win_domain_membership:
        dns_domain_name: wma.local
        domain_admin_user: WMA_Admin
        domain_admin_password: P@ssw0rd2018
        domain_ou_path: "OU=Servers,DC=ansible,DC=vagrant"
        state: domain
      register: domain_state

    - name: Reboot once Domain Controller is created
      win_reboot:
      when: domain_state.reboot_required
