- hosts: management
  tasks:
    - name: Install putty
      win_package:
        path: 'https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.70-installer.msi'
        product_id: '{7E8A5A47-BBB1-4768-B81A-4011665FF73B}'
        
    - name: Copy a single file where the source is on the remote host
      win_copy:
        src: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\PuTTY (64-bit)\PuTTY.lnk
        dest: C:\Users\WMA_Admin\Desktop\PuTTY.lnk
        remote_src: yes
      
- hosts: webservers
  tasks:
    - name: Install IIS (Web-Server only)
      win_feature:
        name: Web-Server
        state: present
        
    - name: create Temp directory
      win_file:
        path: C:\temp
        state: directory
    
    - name: Copy certificate
      win_copy:
        src: /home/WMA_Admin/wma.westeurope.cloudapp.azure.com.pfx
        dest: C:\temp\wma.westeurope.cloudapp.azure.com.pfx
        
    - name: import certificate
      win_certificate_store:
        path: C:\temp\wma.westeurope.cloudapp.azure.com.pfx
        state: present
        password: P@ssw0rd2018
      
    - name: Add HTTPS binding
      win_iis_webbinding:
        name: Default Web Site
        protocol: https
        port: 443
        host_header: wma.westeurope.cloudapp.azure.com
        ssl_flags: 1
        certificate_hash: 712a3ccf4cf6ecb8747722b972ff6b0a291ac2b0
        state: present
        
    - name: install url rewrite
      win_package:
        path: 'https://download.microsoft.com/download/1/2/8/128E2E22-C1B9-44A4-BE2A-5859ED1D4592/rewrite_amd64_en-US.msi'
        product_id: '{9BCA2118-F753-4A1E-BCF3-5A820729965C}'
        
- hosts: domaincontroller
  tasks:
    - name: Install AD-Domain-Services feature
      win_feature: >
        name=AD-Domain-Services
        include_management_tools=yes
        include_sub_features=yes
        state=present
        
    - name: Set a single address on the adapter named Ethernet
      win_dns_client:
        adapter_names: Ethernet
        ipv4_addresses: 127.0.0.1
  
    - name: Create Active Directory Domain Controller
      win_domain:
        dns_domain_name: wma.local
        safe_mode_password: P@ssw0rd2018
      register: active_directory_controllers

    - name: Reboot once Domain Controller is created
      win_reboot:
      when: active_directory_controllers.reboot_required
         
- hosts: memberservers
  tasks:
    - name: Set a single address on the adapter named Ethernet
      win_dns_client:
        adapter_names: Ethernet
        ipv4_addresses: 10.0.2.4
        
    - name: Reboot    
      win_reboot:
      
    - name: Wait 300 seconds, but only start checking after 60 seconds
      wait_for_connection:
        delay: 60
        timeout: 300
      
    - name: Add server to domain
      win_domain_membership:
        dns_domain_name: wma.local
        domain_admin_user: WMA_Admin@wma.local
        domain_admin_password: P@ssw0rd2018
        state: domain
      register: domain_state

    - name: Reboot once Domain Controller is created
      win_reboot:
      when: domain_state.reboot_required
      
- hosts: windows
  tasks:
    - name: Move duo login script
      win_copy:
        src: /home/WMA_Admin/duologin.ps1
        dest: C:\Users\WMA_Admin\Documents\duologin.ps1
        
    - name: Download Duo Security
      win_get_url:
        url: https://dl.duosecurity.com/duo-win-login-latest.exe
        dest: C:\Users\WMA_Admin\Documents\duo-win-login-latest.exe
        
    - name: Run remote PowerShell script
      win_shell: C:\Users\WMA_Admin\Documents\duologin.ps1 >> c:\somelog.txt
