- hosts: databaseserver
  tasks:
  - name: Powershell | Check for SQLServer DSC Powershell module
    win_psmodule:
      name: SQLServerDsc
      state: present

  - name: Powershell | Check for Storage DSC Powershell module
    win_psmodule:
      name: StorageDsc
      state: present

  - name: Powershell | Check for ServerManager Powershell module
    win_psmodule:
      name: ServerManager
      state: present

  - name: Powershell | Ensure that DBA Tools module is present
    win_psmodule:
      name: dbatools
      state: present

  - name: Powershell | Check for xNetworking Powershell module
    win_psmodule:
      name: xNetworking
      state: present

  - name: Windows | Install .NET Framework Core
    win_feature:
      name: NET-Framework-Core
      state: present

# Setup SQL Server Pre-Reqs
  - name: Windows | Install .NET Framework 3.5
    win_feature:
      name: NET-Framework-Features
      state: present

  - name: Windows | Install .NET Framework 4.5 Features
    win_feature:
      name: NET-Framework-45-Features
      state: present
      include_sub_features: True

  - name: Windows | Install Windows Process Activation Service
    win_feature:
      name: WAS
      state: present
      include_sub_features: True

